package org.example;
/*
 * This source file was generated by the Gradle 'init' task
 */


import org.example.App;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

public class AppTest {

    private App myApp;
    @BeforeAll
    void constructor() {
        myApp = new App();
    }
    @Test
    public void multiplyTest() {
        assertEquals(5, myApp.multiply(2,2));
    }
}
